In [4]:
import numpy as np

# Normal Python list
py_list = [1, 2, 3, 4, 5]

# NumPy array
arr = np.array([1, 2, 3, 4, 5])

print("List:", py_list)
print("Array:", arr)
print("Shape:", arr.shape)   # how many elements
print("Type:", arr.dtype)    # what kind of numbers

List: [1, 2, 3, 4, 5]
Array: [1 2 3 4 5]
Shape: (5,)
Type: int64


In [5]:
# 2 rows, 3 columns
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

print(arr2d)
print("Shape:", arr2d.shape)   # (2, 3) → 2 rows, 3 cols
print("Rows:", arr2d.shape[0])
print("Cols:", arr2d.shape[1])

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Rows: 2
Cols: 3


In [6]:
import time

big = np.arange(1000000)  # 1 million numbers

# Slow way — Python loop
start = time.time()
result = [x * 2 for x in big]
print("Loop time:", round(time.time() - start, 4), "sec")

# Fast way — NumPy
start = time.time()
result = big * 2
print("NumPy time:", round(time.time() - start, 4), "sec")

Loop time: 0.1385 sec
NumPy time: 0.0152 sec


In [7]:
arr = np.array([1, 2, 3, 4, 5])

# Applies to EVERY element automatically
print(arr + 10)    # [11 12 13 14 15]
print(arr * 3)     # [3  6  9 12 15]
print(arr ** 2)    # [1  4  9 16 25]

[11 12 13 14 15]
[ 3  6  9 12 15]
[ 1  4  9 16 25]


In [8]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
print(np.zeros((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
arr = np.array([4, 7, 2, 9, 1, 5, 8, 3, 6])
print("Mean:", arr.mean())
print("Max:", arr.max())
print("Min:", arr.min())

Mean: 5.0
Max: 9
Min: 1


In [12]:
arr = np.arange(1, 13)
print(arr.reshape(3, 4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
print(a * b)

[ 10  40  90 160]


In [14]:
arr = np.array([3, 7, 1, 9, 4, 6, 2, 8, 5])
print(arr[arr > 5])

[7 9 6 8]


In [15]:
arr = np.array([3, 7, 1, 9, 4, 6, 2, 8, 5])
print(np.sort(arr))

[1 2 3 4 5 6 7 8 9]


In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.vstack([a, b]))

[[1 2 3]
 [4 5 6]]


In [17]:
print(np.random.rand(5))

[0.88072049 0.42495376 0.12654579 0.14794234 0.64592337]


In [18]:
import time

sizes = [1000, 10000, 100000, 1000000]

for size in sizes:
    arr = np.arange(size)
    
    # Python loop
    start = time.time()
    result = [x ** 2 for x in arr]
    loop_time = round(time.time() - start, 5)
    
    # NumPy
    start = time.time()
    result = arr ** 2
    numpy_time = round(time.time() - start, 5)
    
    print(f"Size {size:>8} → Loop: {loop_time}s | NumPy: {numpy_time}s")

Size     1000 → Loop: 0.00058s | NumPy: 7e-05s
Size    10000 → Loop: 0.00179s | NumPy: 0.00022s
Size   100000 → Loop: 0.02024s | NumPy: 0.00197s
Size  1000000 → Loop: 0.10347s | NumPy: 0.0122s
